"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.wrappers_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Redis(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _TaskType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TaskTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Redis._TaskType.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: Redis._TaskType.ValueType  # 0
        GET_INFO: Redis._TaskType.ValueType  # 1
        GET_SLOWLOG: Redis._TaskType.ValueType  # 2
        RUN_COMMAND: Redis._TaskType.ValueType  # 3

    class TaskType(_TaskType, metaclass=_TaskTypeEnumTypeWrapper): ...
    UNKNOWN: Redis.TaskType.ValueType  # 0
    GET_INFO: Redis.TaskType.ValueType  # 1
    GET_SLOWLOG: Redis.TaskType.ValueType  # 2
    RUN_COMMAND: Redis.TaskType.ValueType  # 3

    @typing_extensions.final
    class GetInfo(google.protobuf.message.Message):
        """Fetch server statistics via the Redis INFO command."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SECTION_FIELD_NUMBER: builtins.int
        @property
        def section(self) -> google.protobuf.wrappers_pb2.StringValue:
            """Optional INFO section (e.g. "memory", "clients", "stats", "replication").
            When empty, the default INFO output is returned.
            """
        def __init__(
            self,
            *,
            section: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["section", b"section"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["section", b"section"]) -> None: ...

    @typing_extensions.final
    class GetSlowlog(google.protobuf.message.Message):
        """Fetch the Redis slow query log via SLOWLOG GET."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        LIMIT_FIELD_NUMBER: builtins.int
        @property
        def limit(self) -> google.protobuf.wrappers_pb2.UInt64Value:
            """Number of entries to return. Defaults to 10 when unset."""
        def __init__(
            self,
            *,
            limit: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["limit", b"limit"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["limit", b"limit"]) -> None: ...

    @typing_extensions.final
    class RunCommand(google.protobuf.message.Message):
        """Run a single read-only Redis command (e.g. "DBSIZE", "GET foo",
        "MEMORY USAGE key", "CLIENT LIST"). Write/administrative commands are
        rejected by the connector.
        """

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        COMMAND_FIELD_NUMBER: builtins.int
        @property
        def command(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            command: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["command", b"command"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["command", b"command"]) -> None: ...

    TYPE_FIELD_NUMBER: builtins.int
    GET_INFO_FIELD_NUMBER: builtins.int
    GET_SLOWLOG_FIELD_NUMBER: builtins.int
    RUN_COMMAND_FIELD_NUMBER: builtins.int
    type: global___Redis.TaskType.ValueType
    @property
    def get_info(self) -> global___Redis.GetInfo: ...
    @property
    def get_slowlog(self) -> global___Redis.GetSlowlog: ...
    @property
    def run_command(self) -> global___Redis.RunCommand: ...
    def __init__(
        self,
        *,
        type: global___Redis.TaskType.ValueType = ...,
        get_info: global___Redis.GetInfo | None = ...,
        get_slowlog: global___Redis.GetSlowlog | None = ...,
        run_command: global___Redis.RunCommand | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["get_info", b"get_info", "get_slowlog", b"get_slowlog", "run_command", b"run_command", "task", b"task"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["get_info", b"get_info", "get_slowlog", b"get_slowlog", "run_command", b"run_command", "task", b"task", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["task", b"task"]) -> typing_extensions.Literal["get_info", "get_slowlog", "run_command"] | None: ...

global___Redis = Redis
