# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/playbooks/source_task_definitions/redis_task.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9protos/playbooks/source_task_definitions/redis_task.proto\x12\x10protos.playbooks\x1a\x1egoogle/protobuf/wrappers.proto\"\xe5\x03\n\x05Redis\x12.\n\x04type\x18\x01 \x01(\x0e\x32 .protos.playbooks.Redis.TaskType\x12\x33\n\x08get_info\x18\x02 \x01(\x0b\x32\x1f.protos.playbooks.Redis.GetInfoH\x00\x12\x39\n\x0bget_slowlog\x18\x03 \x01(\x0b\x32\".protos.playbooks.Redis.GetSlowlogH\x00\x12\x39\n\x0brun_command\x18\x04 \x01(\x0b\x32\".protos.playbooks.Redis.RunCommandH\x00\x1a\x38\n\x07GetInfo\x12-\n\x07section\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x1a\x39\n\nGetSlowlog\x12+\n\x05limit\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\x1a;\n\nRunCommand\x12-\n\x07\x63ommand\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\"G\n\x08TaskType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08GET_INFO\x10\x01\x12\x0f\n\x0bGET_SLOWLOG\x10\x02\x12\x0f\n\x0bRUN_COMMAND\x10\x03\x42\x06\n\x04taskb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.playbooks.source_task_definitions.redis_task_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REDIS._serialized_start=112
  _REDIS._serialized_end=597
  _REDIS_GETINFO._serialized_start=340
  _REDIS_GETINFO._serialized_end=396
  _REDIS_GETSLOWLOG._serialized_start=398
  _REDIS_GETSLOWLOG._serialized_end=455
  _REDIS_RUNCOMMAND._serialized_start=457
  _REDIS_RUNCOMMAND._serialized_end=516
  _REDIS_TASKTYPE._serialized_start=518
  _REDIS_TASKTYPE._serialized_end=589
# @@protoc_insertion_point(module_scope)
